sonar.projectKey=NTCoding_living-architecture
sonar.organization=nick-tune-org
sonar.projectName=living-architecture
sonar.host.url=https://sonarcloud.io

sonar.sources=packages,apps
sonar.tests=packages,apps
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts,**/*.spec.tsx,**/*.test.tsx
sonar.exclusions=**/node_modules/**,**/dist/**,**/test-output/**,apps/docs/scripts/**,packages/*/scripts/**,**/*-test-fixtures.ts,**/*-fixtures.ts,**/vitest.config.mts,**/vitest.browser.config.mts
sonar.coverage.exclusions=packages/riviere-extract-config/src/types.ts,packages/riviere-role-enforcement/role-enforcement-plugin.mjs,**/index.ts,**/vitest.config.mts,**/vitest.browser.config.mts,**/test/**,**/esbuild.config.mjs
sonar.cpd.exclusions=**/vitest.config.mts,**/vitest.browser.config.mts,**/vite.config.ts

sonar.javascript.lcov.reportPaths=packages/*/test-output/vitest/coverage/lcov.info,apps/*/test-output/vitest/coverage/lcov.info

sonar.typescript.tsconfigPaths=tsconfig.base.json
