export {
  FOCUS_MODE_TRANSITIONS,
  FOCUS_MODE_NODE_SCALES,
  FOCUS_MODE_OPACITY,
  FOCUS_MODE_STROKES,
  FOCUS_MODE_TEXT,
  UNFOCUSED_NODE_STROKE_COLOR,
} from '@/platform/domain/focus-mode-constants'
