import { z } from 'zod'

export const responseActionSchema = z.enum(['fixed', 'rejected'])
/** @riviere-role value-object */
export type ResponseAction = z.infer<typeof responseActionSchema>

const REJECTED_MIN_LENGTH = 300
const REJECTED_LENGTH_ERROR = `Rejected feedback requires a detailed justification (minimum ${REJECTED_MIN_LENGTH} characters).

This limit exists to prevent lazy dismissals like "out of scope" without explanation.
Your rejection must explain:
- WHY the feedback doesn't apply
- If claiming "out of scope": which specific file was NOT modified in this PR

Remember: If the file was modified in this PR, the feedback is probably NOT out of scope.`

export const respondToFeedbackInputSchema = z
  .object({
    threadId: z.string().min(1, { message: 'threadId is required' }),
    action: responseActionSchema,
    message: z.string().min(1, { message: 'message is required' }),
  })
  .refine((data) => data.action !== 'rejected' || data.message.length >= REJECTED_MIN_LENGTH, {
    message: REJECTED_LENGTH_ERROR,
    path: ['message'],
  })
/** @riviere-role value-object */
export type RespondToFeedbackInput = z.infer<typeof respondToFeedbackInputSchema>

const respondToFeedbackOutputSchema = z.object({
  success: z.boolean(),
  threadId: z.string(),
  action: responseActionSchema,
  error: z.string().optional(),
})
/** @riviere-role value-object */
export type RespondToFeedbackOutput = z.infer<typeof respondToFeedbackOutputSchema>

const GENERATED_BY_SUFFIX = '\n\n---\n*Generated by Claude Code*'

/** @riviere-role domain-service */
export function formatReplyBody(action: ResponseAction, message: string): string {
  const prefix = action === 'fixed' ? '✅ **Fixed**' : '❌ **Rejected**'
  return `${prefix}: ${message}${GENERATED_BY_SUFFIX}`
}
