import {
  describe, it, expect 
} from 'vitest'
import {
  formatReplyBody, respondToFeedbackInputSchema 
} from './feedback-response'

describe('formatReplyBody', () => {
  it('formats fixed action with message', () => {
    const result = formatReplyBody('fixed', 'Applied the suggested change')

    expect(result).toStrictEqual(
      '✅ **Fixed**: Applied the suggested change\n\n---\n*Generated by Claude Code*',
    )
  })

  it('formats rejected action with message', () => {
    const result = formatReplyBody('rejected', 'This is intentional design')

    expect(result).toStrictEqual(
      '❌ **Rejected**: This is intentional design\n\n---\n*Generated by Claude Code*',
    )
  })
})

describe('respondToFeedbackInputSchema', () => {
  it('validates valid fixed input', () => {
    const input = {
      threadId: 'PRRT_123',
      action: 'fixed',
      message: 'Done',
    }

    const result = respondToFeedbackInputSchema.parse(input)

    expect(result.action).toStrictEqual('fixed')
  })

  it('validates valid rejected input with detailed justification', () => {
    const detailedMessage =
      'This feedback suggests adding error handling, but the error handling already exists in the parent component (src/components/ErrorBoundary.tsx). ' +
      'The current implementation deliberately re-throws to let the boundary catch it. ' +
      'Adding a try-catch here would swallow errors and break the error reporting flow. ' +
      'See ADR-015 for the error handling strategy.'

    const input = {
      threadId: 'PRRT_456',
      action: 'rejected',
      message: detailedMessage,
    }

    const result = respondToFeedbackInputSchema.parse(input)

    expect(result.action).toStrictEqual('rejected')
  })

  it('rejects lazy rejected feedback with short message', () => {
    const input = {
      threadId: 'PRRT_456',
      action: 'rejected',
      message: 'Out of scope: Pre-existing code not modified in this PR',
    }

    expect(() => respondToFeedbackInputSchema.parse(input)).toThrow(
      'Rejected feedback requires a detailed justification',
    )
  })

  it('accepts rejected feedback with exactly minimum length', () => {
    const exactlyMinLength = 'a'.repeat(300)
    const input = {
      threadId: 'PRRT_789',
      action: 'rejected',
      message: exactlyMinLength,
    }

    const result = respondToFeedbackInputSchema.parse(input)

    expect(result.action).toStrictEqual('rejected')
  })

  it('rejects empty threadId', () => {
    const input = {
      threadId: '',
      action: 'fixed',
      message: 'Done',
    }

    expect(() => respondToFeedbackInputSchema.parse(input)).toThrow('threadId is required')
  })

  it('rejects empty message', () => {
    const input = {
      threadId: 'PRRT_123',
      action: 'fixed',
      message: '',
    }

    expect(() => respondToFeedbackInputSchema.parse(input)).toThrow('message is required')
  })

  it('rejects invalid action', () => {
    const input = {
      threadId: 'PRRT_123',
      action: 'invalid',
      message: 'Done',
    }

    expect(() => respondToFeedbackInputSchema.parse(input)).toThrow('Invalid option')
  })
})
