import {
  describe, it, expect, vi, beforeEach, afterEach 
} from 'vitest'

const {
  mockAddThreadReply, mockResolveThread 
} = vi.hoisted(() => ({
  mockAddThreadReply: vi.fn(),
  mockResolveThread: vi.fn(),
}))

vi.mock('../../../platform/infra/external-clients/github/rest-client', () => ({
  github: {
    addThreadReply: mockAddThreadReply,
    resolveThread: mockResolveThread,
  },
}))

import {
  respondToFeedback, executeRespondToFeedback 
} from './respond-to-feedback'

class ExitSignal extends Error {
  constructor() {
    super('exit called')
    this.name = 'ExitSignal'
  }
}

describe('respondToFeedback', () => {
  beforeEach(() => {
    vi.clearAllMocks()
    mockAddThreadReply.mockResolvedValue(undefined)
    mockResolveThread.mockResolvedValue(undefined)
  })

  it('calls github addThreadReply with formatted body', async () => {
    await respondToFeedback({
      threadId: 'PRRT_123',
      action: 'fixed',
      message: 'Applied the fix',
    })

    expect(mockAddThreadReply).toHaveBeenCalledWith(
      'PRRT_123',
      '✅ **Fixed**: Applied the fix\n\n---\n*Generated by Claude Code*',
    )
  })

  it('calls github resolveThread when action is rejected', async () => {
    const detailedRejection =
      'This feedback suggests adding null checks, but the null case is handled at the API boundary in src/api/validator.ts. ' +
      'The domain layer receives validated data only. Adding redundant checks here would violate the fail-fast principle ' +
      'and create unnecessary defensive programming. See ADR-012 for validation strategy.'

    await respondToFeedback({
      threadId: 'PRRT_456',
      action: 'rejected',
      message: detailedRejection,
    })

    expect(mockResolveThread).toHaveBeenCalledWith('PRRT_456')
  })

  it('returns success result with input details', async () => {
    const result = await respondToFeedback({
      threadId: 'PRRT_789',
      action: 'fixed',
      message: 'Done',
    })

    expect(result).toStrictEqual({
      success: true,
      threadId: 'PRRT_789',
      action: 'fixed',
    })
  })

  it('validates input and rejects empty threadId', async () => {
    await expect(
      respondToFeedback({
        threadId: '',
        action: 'fixed',
        message: 'Done',
      }),
    ).rejects.toThrow('threadId is required')
  })

  it('validates input and rejects empty message', async () => {
    await expect(
      respondToFeedback({
        threadId: 'PRRT_123',
        action: 'fixed',
        message: '',
      }),
    ).rejects.toThrow('message is required')
  })
})

describe('executeRespondToFeedback', () => {
  const originalArgv = process.argv
  const capturedOutput: string[] = []

  beforeEach(() => {
    vi.clearAllMocks()
    capturedOutput.length = 0
    mockAddThreadReply.mockResolvedValue(undefined)
    mockResolveThread.mockResolvedValue(undefined)
    vi.spyOn(console, 'log').mockImplementation((msg: string) => {
      capturedOutput.push(msg)
    })
    vi.spyOn(process, 'exit').mockImplementation(() => {
      throw new ExitSignal()
    })
  })

  afterEach(() => {
    process.argv = originalArgv
    vi.restoreAllMocks()
  })

  it('parses CLI args and calls respondToFeedback', async () => {
    process.argv = [
      'node',
      'script',
      '--thread-id',
      'PRRT_cli',
      '--action',
      'fixed',
      '--message',
      'CLI message',
    ]

    await executeRespondToFeedback()

    expect(mockAddThreadReply).toHaveBeenCalledWith(
      'PRRT_cli',
      '✅ **Fixed**: CLI message\n\n---\n*Generated by Claude Code*',
    )
  })

  it('logs success output as JSON', async () => {
    const detailedRejection =
      'This feedback suggests using async/await instead of Promise chains, but the current implementation uses Promise.all ' +
      'for parallel execution which cannot be easily replicated with sequential async/await. The Promise chain approach here ' +
      'is intentional for performance. Changing to async/await would serialize the operations and increase latency by 3x.'

    process.argv = [
      'node',
      'script',
      '--thread-id',
      'PRRT_json',
      '--action',
      'rejected',
      '--message',
      detailedRejection,
    ]

    await executeRespondToFeedback()

    const output: unknown = JSON.parse(capturedOutput[0])
    expect(output).toStrictEqual({
      success: true,
      threadId: 'PRRT_json',
      action: 'rejected',
    })
  })

  it('throws when threadId missing', async () => {
    process.argv = ['node', 'script', '--action', 'fixed', '--message', 'Missing threadId']

    await expect(executeRespondToFeedback()).rejects.toThrow('invalid_type')
  })

  it('throws when action missing', async () => {
    process.argv = ['node', 'script', '--thread-id', 'PRRT_123', '--message', 'Missing action']

    await expect(executeRespondToFeedback()).rejects.toThrow('invalid_type')
  })

  it('throws when message missing', async () => {
    process.argv = ['node', 'script', '--thread-id', 'PRRT_123', '--action', 'fixed']

    await expect(executeRespondToFeedback()).rejects.toThrow('invalid_type')
  })

  it('throws when action is invalid', async () => {
    process.argv = [
      'node',
      'script',
      '--thread-id',
      'PRRT_123',
      '--action',
      'invalid',
      '--message',
      'Invalid action',
    ]

    await expect(executeRespondToFeedback()).rejects.toThrow('Invalid option')
  })
})
